### ISSUE TITLE
reharding the 江南大学数据\数据/ib600_2.csv

### ISSUE THREAD

**Issue by kashyaprakshith** [ZhaoZhibin/UDTL#2]
hello!!
i was runnimg the train_base.py i was not babe to find the 江南大学数据\数据/ib600_2.csv file and it is raising error "OSError: /tmp/D:/Data\江南大学数据\数据/ib600_2.csv not found." please could you guide me to find the .csv file?

**Comment by yshlbm** [comment]
> hello!! i was runnimg the train_base.py i was not babe to find the 江南大学数据\数据/ib600_2.csv file and it is raising error "OSError: /tmp/D:/Data\江南大学数据\数据/ib600_2.csv not found." please could you guide me to find the .csv file?

read the README.md file

**Comment by kashyaprakshith** [comment]
i read it multiple times and i am not able to find it, is it a part of JNU Bearing Dataset mechanical dataset?
